#!/bin/sh

if [ $# -ne 2 ]; then
	echo "Usage: $0 add|rm <path>"
	exit 1
fi

case $1 in
	add)
		echo "
BEGIN;
DELETE FROM modules WHERE module_path = :'path';
DELETE FROM modules WHERE module_path LIKE :'path' || '/%';
INSERT INTO blocklist (import_path) VALUES (:'path');
COMMIT;
" | psql -v path=$2
;;

	rm)
		echo "
BEGIN;
DELETE FROM blocklist WHERE import_path = :'path';
COMMIT;
" | psql -v path=$2
;;

esac
