//go:build ignore
// +build ignore

package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
)

const template = `// Automatically generated by go generate. DO NOT EDIT

package platforms

var platforms = %#v

var platformsMap = %#v
`

func main() {
	output := flag.String("output", "data.go", "output file")
	flag.Parse()

	platformsMap := map[string]struct{}{}
	cmd := exec.Command("go", "tool", "dist", "list")
	o, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}
	platforms := strings.Fields(string(o))
	for _, platform := range platforms {
		platformsMap[platform] = struct{}{}
	}

	f, err := os.Create(*output)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	fmt.Fprintf(f, template, platforms, platformsMap)
}
