//go:build ignore
// +build ignore

package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path"
	"runtime"
	"sort"
	"strings"
)

const template = `// Automatically generated by go generate. DO NOT EDIT

package stdlib

var stdlibPackages = %#v

var stdlibPackagesMap = %#v
`

func main() {
	output := flag.String("output", "data.go", "output file")
	flag.Parse()

	gosrc := path.Join(runtime.GOROOT(), "src")

	pkgsMap := map[string]struct{}{}
	cmd := exec.Command("find", gosrc, "-type", "d", "-mindepth", "1")
	o, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}
	for _, pkg := range strings.Fields(string(o)) {
		pkg = strings.TrimPrefix(pkg, gosrc)
		pkg = strings.TrimPrefix(pkg, "/")
		if pkg == "vendor" ||
			strings.HasPrefix(pkg, "vendor/") ||
			strings.Contains(pkg, "/vendor/") {
			continue
		}
		pkgsMap[pkg] = struct{}{}
	}

	pkgs := []string{}
	for pkg := range pkgsMap {
		// Hide cmd and internal packages from the list
		if strings.HasPrefix(pkg, "cmd/") ||
			strings.HasPrefix(pkg, "internal/") ||
			strings.Contains(pkg, "/internal/") ||
			strings.HasSuffix(pkg, "/internal") {
			continue
		}
		pkgs = append(pkgs, pkg)
	}
	sort.Strings(pkgs)

	f, err := os.Create(*output)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	fmt.Fprintf(f, template, pkgs, pkgsMap)
}
